/** Public library surface. Grows one component per milestone (PLAN §6). */
export {
  CapabilityDifferContractError,
  CapabilityDifferError,
  diffCapabilities,
  diffManifestCapabilities,
  type CapabilityChange,
  type CapabilityDiffDiagnostic,
  type CapabilityDiffResult,
  type CapabilityFinding,
  type FindingSeverity,
  type ShapeFinding,
  type ShapeRuleId,
} from "./core/capability-differ.js";
export {
  CapabilityAnalysisPipelineConfigurationError,
  CapabilityAnalysisPipelineContractError,
  CapabilityAnalysisPipelineError,
  ManifestAnalysisPipelineConfigurationError,
  ManifestAnalysisPipelineContractError,
  ManifestAnalysisPipelineError,
  analyzeChangedPackages,
  analyzeManifestPackages,
  type AnalysisSide,
  type AnalyzedPackage,
  type CapabilityAnalysisOptions,
  type CapabilityAnalysisRun,
  type ManifestAnalysisOptions,
  type ManifestAnalysisRun,
  type PackageAnalysisFailure,
  type PackageAnalysisResult,
  type UnavailablePackage,
} from "./core/manifest-analysis-pipeline.js";
export {
  CAPABILITY_SET_SCHEMA_VERSION,
  type AnalysisDiagnostic,
  type AnalysisDiagnosticKind,
  type Capability,
  type CapabilityLocation,
  type CapabilitySet,
  type CodeCapability,
  type CodeCapabilityKind,
  type CommandEntrypointCapability,
  type ContentDigest,
  type DependencyCapability,
  type Evidence,
  type EvidenceList,
  type InstallHook,
  type InstallHookCapability,
  type InstallScriptLocation,
  type PackageSubject,
  type RuntimeConstraintCapability,
} from "./core/contract/capability-set.js";
export type {
  ChangedPackage,
  LockfileDiffResult,
  LockfileFinding,
  LockfileFindingKind,
  SkipReason,
  SkippedPackage,
} from "./core/contract/lockfile-diff.js";
export { diffNpmLockfiles } from "./core/npm/lockfile-differ.js";
export {
  FetcherConfigurationError,
  FetcherContractError,
  FetcherError,
  MemoryTarballCache,
  fetchChangedPackages,
  type FetchFailure,
  type FetchFailureKind,
  type FetchPackageResult,
  type FetcherOptions,
  type TarballSide,
  type VerifiedTarball,
} from "./core/npm/fetcher.js";
export {
  ManifestCapabilityExtractorConfigurationError,
  ManifestCapabilityExtractorContractError,
  ManifestCapabilityExtractorError,
  extractNpmManifestCapabilities,
  type AnalyzedManifestCapabilities,
  type ManifestCapabilityExtractorOptions,
  type ManifestCapabilityFailure,
  type ManifestCapabilityFailureKind,
  type ManifestCapabilityResult,
  type UnavailableManifestCapabilities,
} from "./core/npm/manifest-capability-extractor.js";
export {
  JavaScriptCapabilityExtractorConfigurationError,
  JavaScriptCapabilityExtractorContractError,
  JavaScriptCapabilityExtractorError,
  extractNpmJavaScriptCapabilities,
  mergeJavaScriptCapabilityLayer,
  type AstExtractionOptions,
  type JavaScriptCapabilityLayerResult,
} from "./core/npm/javascript-capability-extractor.js";
export {
  REPORT_SCHEMA_VERSION,
  ReporterContractError,
  ReporterError,
  renderJsonReport,
  renderJsonRunReport,
  renderTextReport,
  renderTextRunReport,
  type JsonReport,
  type JsonReportAnalysisIssue,
  type JsonReportDiagnostic,
  type JsonReportFinding,
  type JsonReportLockfileFinding,
  type JsonReportSkippedPackage,
  type JsonRunPackage,
  type JsonRunReport,
  type ReportAnalysisIssueKind,
  type ReportCapability,
  type ReportCommandEntrypointCapability,
  type ReportDependencyCapability,
  type ReportEvidence,
  type ReportInstallHookCapability,
  type ReportPackage,
  type ReportRuntimeConstraintCapability,
  type ReportCodeCapability,
  type JsonReportShapeFinding,
  type SeverityCounts,
} from "./core/reporter.js";
export { SARIF_VERSION, renderSarifReport } from "./core/sarif-reporter.js";
export {
  ExtractorConfigurationError,
  ExtractorError,
  extractVerifiedTarball,
  type ExtractedTarball,
  type ExtractionFailure,
  type ExtractionFailureKind,
  type ExtractionResult,
  type ExtractorOptions,
  type RejectedExtraction,
} from "./core/npm/safe-extractor.js";
export {
  LockfileError,
  MalformedLockfileError,
  UnsupportedLockfileVersionError,
  type LockfileSide,
} from "./core/npm/errors.js";
